line_length:
    - 300 #warning
    - 400 #error
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
function_body_length:
    - 20 #warning
    - 26 #error
closure_body_length:
    - 20 #warning
    - 26 #error
file_length:
    - 500 #warning
    - 600 #error
function_parameter_count:
    - 3 #warning
    - 4 #error
